### ISSUE TITLE
Some UI glitches & query

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#5]
Hey, thank you for continuing this awesome script. I just noticed some minor glitches. In manga, the script is showing "Watching" instead of "Reading". 

![2018-10-10_17-32-59](https://user-images.githubusercontent.com/39864104/46735083-c2d84b00-ccb2-11e8-9bf9-b6326dc46aa3.png)
![slimjet_2018-10-10_17-29-49](https://user-images.githubusercontent.com/39864104/46735084-c2d84b00-ccb2-11e8-9d62-2a071be38c49.png)

Also, I use ublock origin in advanced mode. That is block all third party script & frames. This is causing pictures in Mini MAL to not display. Can you tell me which trackers to allow? 

![2018-10-10_17-30-08](https://user-images.githubusercontent.com/39864104/46735177-12b71200-ccb3-11e8-9b26-50b2be6a3209.png)
![2018-10-10_17-35-48](https://user-images.githubusercontent.com/39864104/46735180-13e83f00-ccb3-11e8-96c5-e7fd2e4d10f1.png)

**Comment by hemlok89** [comment]
Hey thanks, it worked!

**Comment by quietlystorming** [comment]
Also using uBO advanced mode here. Somewhat similarly, actual script icons do not display for me. This also happened in KAL.

![capture](https://user-images.githubusercontent.com/15165087/46742753-af5abf00-cc75-11e8-8eed-e4fee7674bdd.PNG)

**Comment by Karmesinrot** [comment]
@quietlystorming you seem to be blocking remote fonts.

**Comment by lolamtisch** [comment]
No it is a problem in the script I hope with the next release that gets solved. Probably I am going to push it tomorrow

**Comment by lolamtisch** [comment]
Should be fixed in version 0.2.7

**Comment by quietlystorming** [comment]
I actually was blocking third-party fonts but whitelisted them and fixed the icons at the top. After updating and testing with uBO disabled, the help/tooltip icon is still missing though. 

![capture3](https://user-images.githubusercontent.com/15165087/46840359-998dec80-cd90-11e8-8be3-b94041e7f043.PNG)

**Comment by lolamtisch** [comment]
Busy atm, will look into it in the next few days.

**Comment by lolamtisch** [comment]
@quietlystorming Should be fixed in the new release. I replaced the icon with a font icon now. 
Just out of curiosity what system are you using, because it was a normal unicode symbol. I would 
suspect that it is some linux, where that symbol is just not in the system font.

**Comment by quietlystorming** [comment]
Thanks! Looks good now, working perfectly. I've only used it on Win8.1 so far, can't speak for any other platforms.
